from enum import StrEnum


class CaseClass(StrEnum):
    A_MANDATE = "A_MANDATE"
    B_ONEOFF = "B_ONEOFF"
    C_ABANDONED = "C_ABANDONED"


class FailureCategory(StrEnum):
    TEMPORARY_GATEWAY_ERROR = "TEMPORARY_GATEWAY_ERROR"
    TEMPORARY_BANK_ERROR = "TEMPORARY_BANK_ERROR"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    INSTRUMENT_EXPIRED = "INSTRUMENT_EXPIRED"
    INSTRUMENT_INVALID = "INSTRUMENT_INVALID"
    RISK_DECLINE = "RISK_DECLINE"
    MANDATE_INVALID = "MANDATE_INVALID"
    CUSTOMER_ABANDONED = "CUSTOMER_ABANDONED"
    CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED"
    UNKNOWN = "UNKNOWN"


class Recoverability(StrEnum):
    AUTOMATED = "RECOVERABLE_AUTOMATED"
    ASSISTED = "RECOVERABLE_ASSISTED"
    NOT_RECOVERABLE = "NOT_RECOVERABLE"


class ActionType(StrEnum):
    RETRY_MANDATE_CHARGE = "RETRY_MANDATE_CHARGE"
    RESCHEDULE_MANDATE_CHARGE = "RESCHEDULE_MANDATE_CHARGE"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    SEND_REMINDER = "SEND_REMINDER"
    SUGGEST_ALTERNATE_METHOD = "SUGGEST_ALTERNATE_METHOD"
    WAIT = "WAIT"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    STOP = "STOP"


class CaseState(StrEnum):
    OPEN = "OPEN"
    CLASSIFIED = "CLASSIFIED"
    DECIDED = "DECIDED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    SCHEDULED = "SCHEDULED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    EXHAUSTED = "EXHAUSTED"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"


class ConsentState(StrEnum):
    OPTED_IN = "OPTED_IN"
    OPTED_OUT = "OPTED_OUT"
    UNKNOWN = "UNKNOWN"


class VerdictType(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    DOWNGRADE = "DOWNGRADE"
    REQUIRE_HUMAN = "REQUIRE_HUMAN"
