from enum import StrEnum


class CaseClass(StrEnum):
    A_MANDATE = "A_MANDATE"
    B_ONEOFF = "B_ONEOFF"
    C_ABANDONED = "C_ABANDONED"


class FailureCategory(StrEnum):
    TEMPORARY_GATEWAY_ERROR = "TEMPORARY_GATEWAY_ERROR"
    TEMPORARY_BANK_ERROR = "TEMPORARY_BANK_ERROR"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    INSTRUMENT_EXPIRED = "INSTRUMENT_EXPIRED"
    INSTRUMENT_INVALID = "INSTRUMENT_INVALID"
    RISK_DECLINE = "RISK_DECLINE"
    MANDATE_INVALID = "MANDATE_INVALID"
    CUSTOMER_ABANDONED = "CUSTOMER_ABANDONED"
    CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED"
    UNKNOWN = "UNKNOWN"


class Recoverability(StrEnum):
    AUTOMATED = "RECOVERABLE_AUTOMATED"
    ASSISTED = "RECOVERABLE_ASSISTED"
    NOT_RECOVERABLE = "NOT_RECOVERABLE"


class ActionType(StrEnum):
    RETRY_MANDATE_CHARGE = "RETRY_MANDATE_CHARGE"
    RESCHEDULE_MANDATE_CHARGE = "RESCHEDULE_MANDATE_CHARGE"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    SEND_REMINDER = "SEND_REMINDER"
    SUGGEST_ALTERNATE_METHOD = "SUGGEST_ALTERNATE_METHOD"
    WAIT = "WAIT"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    STOP = "STOP"


class CaseState(StrEnum):
    OPEN = "OPEN"
    CLASSIFIED = "CLASSIFIED"
    DECIDED = "DECIDED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    SCHEDULED = "SCHEDULED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    EXHAUSTED = "EXHAUSTED"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"


class ConsentState(StrEnum):
    OPTED_IN = "OPTED_IN"
    OPTED_OUT = "OPTED_OUT"
    UNKNOWN = "UNKNOWN"


class VerdictType(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    DOWNGRADE = "DOWNGRADE"
    REQUIRE_HUMAN = "REQUIRE_HUMAN"


class ReasonCode(StrEnum):
    RULE_FALLBACK = "RULE_FALLBACK"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    LLM_SCHEMA_INVALID = "LLM_SCHEMA_INVALID"
    LLM_INELIGIBLE_ACTION = "LLM_INELIGIBLE_ACTION"
    AMBIGUOUS_TAXONOMY = "AMBIGUOUS_TAXONOMY"
    CUSTOMER_CONTEXT = "CUSTOMER_CONTEXT"


class ConsentChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS = "SMS"


class OrderStatus(StrEnum):
    CREATED = "CREATED"
    ATTEMPTED = "ATTEMPTED"
    PAID = "PAID"
    EXPIRED = "EXPIRED"


class PaymentAttemptStatus(StrEnum):
    CREATED = "CREATED"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"


class ClassifiedBy(StrEnum):
    RULE = "RULE"
    LLM = "LLM"
    HUMAN = "HUMAN"


class DecisionSource(StrEnum):
    RULE = "RULE"
    LLM = "LLM"


class InitiatedBy(StrEnum):
    CUSTOMER = "CUSTOMER"
    RECOVERY_SYSTEM = "RECOVERY_SYSTEM"


class RecoveryResolution(StrEnum):
    RECOVERED = "RECOVERED"
    EXHAUSTED = "EXHAUSTED"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"


class RecoveryActionState(StrEnum):
    SCHEDULED = "SCHEDULED"
    REVALIDATING = "REVALIDATING"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class MessageChannel(StrEnum):
    EMAIL = "EMAIL"
    SMS = "SMS"


class GeneratedBy(StrEnum):
    TEMPLATE = "TEMPLATE"
    LLM = "LLM"


class AuditActor(StrEnum):
    SYSTEM = "SYSTEM"
    RULE = "RULE"
    LLM = "LLM"
    HUMAN = "HUMAN"
    GATEWAY = "GATEWAY"
